### ISSUE TITLE
Can't run games use cx latest version

### ISSUE THREAD

**Issue by mrofisr** [skycoin/cx-games#26]
# OS: Ubuntu Budgie 20.04

## Issue: I can't run make build and make install cx-games, use manual build or use binary on GitHub release pages

![image](https://user-images.githubusercontent.com/31870041/109571046-a1938600-7b1d-11eb-9478-a7d26da3ef7a.png)

**Comment by mrofisr** [comment]
I can't play pacman and pacman-3d
Error message says, I have some module missing

![image](https://user-images.githubusercontent.com/31870041/109666678-fa0c6700-7ba1-11eb-906f-9d4129ab4743.png)
![image](https://user-images.githubusercontent.com/31870041/109666700-fed11b00-7ba1-11eb-8f24-11abcd038418.png)

**Comment by archerixx** [comment]
Running `make build-full` should solve this issue now.

**Comment by mrofisr** [comment]
Okay I'll try it

**Comment by SkycoinSynth** [comment]
Fixed.
