### ISSUE TITLE
manual build generates errors

### ISSUE THREAD

**Issue by Diablo2050** [skycoin/cx-games#27]
OS: Ubuntu 20.04.2 LTS
when running make in pacman :
`cx  \
\
pkg/graphical2d.cx \
\
internal/domain/board.cx \
internal/ghost-graphic.cx \
internal/domain/ghost.cx \
internal/domain/pac-man.cx \
\
cmd/init-and-input.cx \
cmd/time-and-space.cx \
cmd/render.cx \
cmd/game-loop.cx \

[68:32] invalid character U+00A0 in identifier
[68:32] invalid character U+00A0
[57:32] invalid character U+00A0 in identifier
[57:32] invalid character U+00A0
panic: struct 'Begin' not found in package 'gl'

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PostfixExpressionField(0xc000010f70, 0x1, 0x1, 0xc0000189e8, 0x5, 0x1, 0xc000010f60, 0x1)
	/home/amr/Documents/misc/golang/cx/cxgo/actions/postfix.go:313 +0x1e25
github.com/skycoin/cx/cxgo/parser.yyParse(0x97e180, 0xc000816c60, 0xc000816c60)
	/home/amr/Documents/misc/golang/cx/cxgo/parser/cxgo.go:2234 +0x7296
github.com/skycoin/cx/cxgo/parser.Parse(...)
	/home/amr/Documents/misc/golang/cx/cxgo/parser/cxgo.go:18
github.com/skycoin/cx/cxgo/cxgo.ParseSourceCode(0xc0000d6400, 0x9, 0x10, 0xc0000d8400, 0x9, 0x10)
	/home/amr/Documents/misc/golang/cx/cxgo/cxgo/cxgo.go:78 +0x40f
main.parseProgram(0x0, 0x972c98, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/amr/Documents/misc/golang/cx/cmd/cx/main.go:182 +0x436
main.Run(0xc0000c4010, 0x9, 0x9)
	/home/amr/Documents/misc/golang/cx/cmd/cx/main.go:91 +0x36c
main.main()
	/home/amr/Documents/misc/golang/cx/cmd/cx/main.go:24 +0x66
make: *** [Makefile:5: all] Error 2
`

**Comment by Diablo2050** [comment]
when running Cxtetris :
`cx --debug-profile=100 ../2DFWork/* .
parse : 60ms
panic: struct 'Color3f' not found in package 'gl'

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PostfixExpressionField(0xc000207388, 0x1, 0x1, 0xc00086eab8, 0x7, 0xc00086ea90, 0x0, 0x1)
	/home/amr/Documents/misc/golang/cx/cxgo/actions/postfix.go:313 +0x1e25
github.com/skycoin/cx/cxgo/parser.yyParse(0x97e180, 0xc0001fdb90, 0xc0001fdb90)
	/home/amr/Documents/misc/golang/cx/cxgo/parser/cxgo.go:2234 +0x7296
github.com/skycoin/cx/cxgo/parser.Parse(...)
	/home/amr/Documents/misc/golang/cx/cxgo/parser/cxgo.go:18
github.com/skycoin/cx/cxgo/cxgo.ParseSourceCode(0xc0001ea600, 0x2c, 0x40, 0xc000081000, 0x2c, 0x40)
	/home/amr/Documents/misc/golang/cx/cxgo/cxgo/cxgo.go:78 +0x40f
main.parseProgram(0x0, 0x972c98, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/amr/Documents/misc/golang/cx/cmd/cx/main.go:182 +0x436
main.Run(0xc0000c4010, 0xe, 0xe)
	/home/amr/Documents/misc/golang/cx/cmd/cx/main.go:91 +0x36c
main.main()
	/home/amr/Documents/misc/golang/cx/cmd/cx/main.go:24 +0x66
make: *** [Makefile:2: all] Error 2
`

**Comment by SkycoinSynth** [comment]
Great!

**Comment by SkycoinSynth** [comment]
Fixed.
